# -*- coding: utf-8 -*-
"""momox-Ceyda_Akbulut.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hN1J6Xn_NnLyFxqktczV0dYm8DUh292x
"""

#Test case1
from matplotlib.image import imread
from sklearn.cluster import KMeans
import numpy as np
import matplotlib.pyplot as plt

def segment_image():
    image = imread("ireland.jpg")
    # Write your code here.
    pixel_values = image.reshape((-1, 3))
    pixel_values = np.float32(pixel_values)
    #print(pixel_values.shape)
    k = KMeans(n_clusters=2, max_iter=100)
    k.fit(pixel_values)
    cent=k.cluster_centers_
    centers = np.uint8(cent)
    new_img=np.zeros((640*550,3),dtype=np.uint8)
    colors=[]
    for each_col in centers:
        colors.append(each_col)

    for ix in range(new_img.shape[0]):
        new_img[ix]=colors[k.labels_[ix]]
    new_img=new_img.reshape((image.shape))
    plt.imshow(new_img)
    plt.show()

segment_image()

#Test case2
import flask
import json
import traceback
from save import save


app = flask.Flask(__name__)

@app.route("/users", methods=["POST"])
def users():

    name = request.json('name')
    age =  request.json('age')

    if name is None or age is None:
        return flask.jsonify(message={"trace": traceback.format_exc()}, status=400), 400
    if len(name)>32:
        return flask.jsonify(message={"trace": traceback.format_exc()}, status=400), 400
    if (str(age)).isnumeric() ==0:
        return flask.jsonify(message={"trace": traceback.format_exc()}, status=400), 400
    if age<16:
        return flask.jsonify(message={"trace": traceback.format_exc()}, status=400), 400
    save()
    return flask.jsonify(message={"trace": traceback.format_exc()}, status=201), 201

if __name__ == "__main__":
    app.run()